//FETCH ALL TRADES
export const FETCH_TRADE_START = 'FETCH_TRADE_START';
export const FETCH_TRADE_SUCCESS = 'FETCH_TRADE_SUCCESS';
export const FETCH_TRADE_FAILURE = 'FETCH_TRADE_FAILURE';

//FECTH TRADE METADATA
export const FETCH_TRADE_REF_DATA_START = 'FETCH_TRADE_REF_DATA_START';
export const FETCH_TRADE_REF_DATA_SUCCESS = 'FETCH_TRADE_REF_DATA_SUCCESS';
export const FETCH_TRADE_REF_DATA_FAILURE = 'FETCH_TRADE_REF_DATA_FAILURE';


//CRUD OPERATIONS
export const UPADTE_TRADE = 'UPADTE_TRADE'; //EDIT or ADD
export const UPADTE_SELECTED_TRADE = 'UPADTE_SELECTED_TRADE';   //INTERNAL UPDATE
export const DELETE_SELECTED_TRADE = 'DELETE_SELECTED_TRADE';   //DELETE
export const SHOW_DELETE_TRADE = 'SHOW_DELETE_TRADE';   //Show Dialog
export const UPDATE_TRADE_SUCCESS = 'UPDATE_TRADE_SUCCESS';
export const UPDATE_TRADE_FAILURE = 'UPDATE_TRADE_FAILURE';

//AUTH related actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';